services:
  mariadb:
    image: mariadb:latest
    container_name: prueba_convocatoria_mariadb
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: university
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_network

volumes:
  mariadb_data:

networks:
  mariadb_network:
